task:
  name: "Setting Up, Syncing, Building and Uploading...."
  timeout_in: 240m  
  container:
      image: ghcr.io/nguyenhung9xdev2024/docker:arch
      cpu: 2
      memory: 4G
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources...."
      - echo "============================"
      - mkdir ~/OrangeFox_sync
      - cd ~/OrangeFox_sync
      - git clone https://gitlab.com/OrangeFox/sync.git
      - cd ~/OrangeFox_sync/sync/
      - ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/fox_12.1
      - git clone https://github.com/nguyenhung9xdev2022/android_device_samsung_a73xq -b fox-12.1 device/samsung/a73xq
      - source build/envsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_BUILD_DEVICE=<device>
      - export LC_ALL="C"
      - lunch omni_a73xq-eng && mka recoveryimage
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
